--- #YAML:1.0
name:               Term-Shell-Pluggable
version:            0.04
abstract:           Pluggable command-line framework
author:
    - Dmitri Popov <operator@cv.dp-net.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:         5.008008
    Term::Shell:  0
    Test::More:   0
resources:
    bugtracker:  http://github.com/pin/term-shell-pluggable/issues
    repository:  git://github.com/pin/term-shell-pluggable.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
